export const sendOtp = {
    OTP_SEND_REQUEST: "OTP_SEND_REQUEST",
    OTP_SEND_SUCCESS: "OTP_SEND_SUCCESS",
    OTP_SEND_FAILURE: "OTP_SEND_FAILURE",
};

export const verifyOtp = {
    OTP_VERIFY_REQUEST: "OTP_VERIFY_REQUEST",
    OTP_VERIFY_SUCCESS: "OTP_VERIFY_SUCCESS",
    OTP_VERIFY_FAILURE: "OTP_VERIFY_FAILURE",
};