export const userConstant = {
    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
  
    
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
  
    UPDATE_PROFILE_IMG_REQUEST: "UPDATE_PROFILE_IMG_REQUEST",
    UPDATE_PROFILE_IMG_SUCCESS: "UPDATE_PROFILE_IMG_SUCCESS",
    UPDATE_PROFILE_IMG_FAILURE: "UPDATE_PROFILE_IMG_FAILURE",

    GET_PROFILE_INFO_REQUEST:"GET_PROFILE_INFO_REQUEST",
    GET_PROFILE_INFO_SUCCESS:"GET_PROFILE_INFO_SUCCESS",
    GET_PROFILE_INFO_FAILURE:"GET_PROFILE_INFO_FAILURE",
  };